apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tier
  labels:
    app: karsajobs
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        app: karsajobs
        tier: app
    spec:
      containers:
        - name: karsajobs-ui
          image: ghcr.io/fikriyusrihan/karsajobs-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000