apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
  labels:
    app: ecommerce
    service: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shipping
  template:
    metadata:
      labels:
        app: ecommerce
        service: shipping
    spec:
      containers:
        - name: shipping-service-container
          image: ghcr.io/fikriyusrihan/shipping-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: AMQP_HOST
              value: "rabbitmq-cluster.ecommerce"
            - name: AMQP_PORT
              value: "5672"
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: username
            - name: AMQP_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: password