apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deployment
  labels:
    app: ecommerce
    service: shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      service: shipping
  template:
    metadata:
      labels:
        app: ecommerce
        service: shipping
    spec:
      containers:
        - name: shipping-service-container
          image: ghcr.io/fikriyusrihan/shipping-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"

            # TODO: Revisit this after configuring RabbitMQ on Kubernetes
            - name: AMQP_URL
              value: "amqp://default_user_ZEHFr3NHCZ7QsKZORT_:QI4KZHcEkZEawQq-e8NZKyYP4Pnfdix9@rabbitmq-cluster.ecommerce:5672"