version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run: hadolint Dockerfile
  test-app:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: docker:18.09.1-git
    steps:
      - checkout
      - setup_remote_docker
      - run: build -t fikriyusrihan/karsajobs:latest .
      - run: docker login ghcr.io -u $DOCKER_USER -p $DOCKER_PASS
      - run: push ghcr.io/fikriyusrihan/karsajobs:latest
workflows:
    version: 2
    build-and-test:
        jobs:
        - lint-dockerfile
        - test-app:
            requires:
                - lint-dockerfile
        - build-app-karsajobs:
            requires:
                - test-app