apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: karsajobs
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs
      tier: data
  serviceName: mongo
  template:
    metadata:
      labels:
        app: karsajobs
        tier: data
    spec:
      containers:
        - name: mongo
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db

            - name: mongo-config-map
              mountPath: /config
              readOnly: true

            - name: mongo-secret-credential
              mountPath: /etc/mongo-credentials
              readOnly: true

      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim

        - name: mongo-config-map
          configMap:
            name: mongo-config
            items:
              - key: mongo.conf
                path: mongo.conf

        - name: mongo-secret-credential
          secret:
            secretName: mongo-secret
            items:
              - key: MONGO_ROOT_USERNAME
                path: MONGO_ROOT_USERNAME

              - key: MONGO_ROOT_PASSWORD
                path: MONGO_ROOT_PASSWORD
